version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stream_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  keydb:
    image: eqalpha/keydb:latest
    command: keydb-server --requirepass streamerroom_keydb_password
    ports:
      - "6379:6379"
    volumes:
      - keydb_data:/data

volumes:
  db_data:
  keydb_data:
